/**
 * Central event registry for Hapbeat Arcade — the single source of truth that
 * couples a logical game event to (1) the device haptic event id, (2) the
 * browser-audio placeholder clip, and (3) a baseline gain.
 *
 * The TUNING.md / tuning.csv tables are generated by hand from this map. Keep
 * them in sync when you add or retune an event (final tuning is the user's).
 *
 * `hapticEvent` ids MUST match the deployed kit (demo-kit/hapbeat-arcade-manifest.json).
 * `audioClip` paths are relative to examples/games/ (served over HTTP).
 */

export const EVENTS = {
  // ── Maze ────────────────────────────────────────────────────────────────
  maze_bump: {
    game: "maze",
    hapticEvent: "hapbeat-arcade.maze_bump",
    audioClip: "demo-kit/install-clips/z5_shot_light.wav",
    gain: 0.5,
    note: "壁に接触。実 gain は接触速度で 0.3–0.9 にスケール。",
  },
  maze_goal: {
    game: "maze",
    hapticEvent: "hapbeat-arcade.maze_goal",
    audioClip: "demo-kit/install-clips/z2_door_unlock.wav",
    gain: 0.6,
    note: "ゴール到達（ポジティブ）。",
  },
  maze_fail: {
    game: "maze",
    hapticEvent: "hapbeat-arcade.maze_fail",
    audioClip: "demo-kit/install-clips/z2_door_slam.wav",
    gain: 0.7,
    note: "Expert 即死モードで壁に当たった時。",
  },

  // ── Rhythm ──────────────────────────────────────────────────────────────
  rhythm_cue: {
    game: "rhythm",
    hapticEvent: "hapbeat-arcade.rhythm_cue",
    audioClip: "demo-kit/install-clips/z4_slider_tick.wav",
    gain: 0.45,
    note: "各拍の触覚キュー（触覚メトロノーム）。叩く瞬間に発火。",
  },
  rhythm_hit: {
    game: "rhythm",
    hapticEvent: "hapbeat-arcade.rhythm_hit",
    audioClip: "demo-kit/install-clips/z1_pin_hit.wav",
    gain: 0.5,
    note: "判定成功の確認。",
  },
  rhythm_combo: {
    game: "rhythm",
    hapticEvent: "hapbeat-arcade.rhythm_combo",
    audioClip: "demo-kit/install-clips/z5_tar_hit_light.wav",
    gain: 0.55,
    note: "10 コンボごとの節目フィードバック。",
  },

  // ── Hot & Cold ──────────────────────────────────────────────────────────
  hot_pulse: {
    game: "hotcold",
    hapticEvent: "hapbeat-arcade.hot_pulse",
    audioClip: "demo-kit/install-clips/z1_pin_hit.wav",
    gain: 0.4,
    note: "近接パルス。gain と間隔が近さでスケール（0.15–1.0 / 600–90ms）。",
  },
  hot_found: {
    game: "hotcold",
    hapticEvent: "hapbeat-arcade.hot_found",
    audioClip: "demo-kit/install-clips/z5_tar_hit_heavy.wav",
    gain: 0.6,
    note: "ターゲット発見（強い当たり）。",
  },
  hot_timeout: {
    game: "hotcold",
    hapticEvent: "hapbeat-arcade.hot_timeout",
    audioClip: "demo-kit/install-clips/z2_door_slam.wav",
    gain: 0.7,
    note: "制限時間切れ（フェイル）。",
  },

  // ── Reflex (Quick Draw) ─────────────────────────────────────────────────
  reflex_go: {
    game: "reflex",
    hapticEvent: "hapbeat-arcade.reflex_go",
    audioClip: "demo-kit/install-clips/z1_pin_hit.wav",
    gain: 0.75,
    note: "GO 合図。視覚 OFF でも反応できる強く鋭い単発が要。最重要。",
  },
  reflex_foul: {
    game: "reflex",
    hapticEvent: "hapbeat-arcade.reflex_foul",
    audioClip: "demo-kit/install-clips/z2_door_slam.wav",
    gain: 0.6,
    note: "お手つき（フライング）。はっきり「ダメ」と分かる。",
  },
  reflex_win: {
    game: "reflex",
    hapticEvent: "hapbeat-arcade.reflex_win",
    audioClip: "demo-kit/install-clips/z5_tar_hit_heavy.wav",
    gain: 0.6,
    note: "好成績の締め（全ラウンド完了時）。",
  },
};

/** All distinct audio clip URLs referenced by the registry (for preloading). */
export function clipUrls() {
  return [...new Set(Object.values(EVENTS).map((e) => e.audioClip))];
}
